pages:
      stage: deploy
      script:
        - npm install # or yarn install
        - npm run build # or yarn build
        - mv dist public # Move build output to 'public' for GitLab Pages
      artifacts:
        paths:
          - public
      only:
        - web # Or your desired branch for deployment