version: '3.7'
services:
  mariadb:
     container_name: web-mariadb-12
     hostname: mariadb
     image: mariadb:10.5
     restart: always
     environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 12_CalculatorDb
      MARIADB_USER: root
      MARIADB_PASSWORD: password
     ports:
      - "0.0.0.0:5052:3306"

  web:
    container_name: 12_Calculator
    hostname: app
    build: .
    ports:
      - "0.0.0.0:5012:5012"